controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

ajax_add_value_to_session:
  path: /ajax/add-value-to-session
  controller: App\Controller\SessionController::addValueToSession
  methods: [POST]

ajax_delete_product:
    path: /ajax/delete_product
    controller: App\Controller\SessionController::deleteProduct
    methods: [POST]

ajax_remove_cart:
    path: /ajax/remove_cart
    controller: App\Controller\SessionController::removeCart
    methods: [POST]

ajax_add_reviews_product:
    path: /ajax/add_reviews_product
    controller: App\Controller\SessionController::addReviewsProduct
    methods: [POST]

ajax_up_vote_product_review:
    path: /ajax/up_vote_product_review
    controller: App\Controller\SessionController::upVoteProductReview
    methods: [POST]

ajax_remove_reviews_product:
    path: /ajax/remove_reviews_product
    controller: App\Controller\SessionController::removeReviewsProduct
    methods: [POST]

ajax_add_delivery:
    path: /ajax/add_delivery
    controller: App\Controller\SessionController::addDelivery

ajax_remove_delivery:
    path: /ajax/remove_delivery
    controller: App\Controller\SessionController::removeDelivery
    methods: [POST]

ajax_order_from_buyers:
    path: /ajax/order_from_buyers
    controller: App\Controller\SessionController::orderFromBuyers
    methods: [POST]

ajax_my_orders:
    path: /ajax/my_orders
    controller: App\Controller\SessionController::myOrders
    methods: [POST]
